services:
  tg-bot:
    build:
      context: .
    volumes:
      - .:/tgbot_drugoy
    environment:
      - DB_HOST=database
      - DB_NAME=tgbot
      - DB_USER=postgres
      - DB_PASS=123456
    command: >
      sh -c "python app.py"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=tgbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5436:5432
    expose:
      - 5436
    volumes:
      - tgbot_drugoy_data2:/var/lib/postgresql/data


volumes:
  tgbot_drugoy_data2:
